sonar.host.url=https://sonarcloud.io
sonar.organization=paion-data
sonar.projectKey=paion-data_nexusgraph
sonar.projectName=nexusgraph
sonar.sources=nexusgraph
sonar.cpd.exclusions=nexusgraph/cypress/e2e/editor.spec.cy.ts
sonar.cpd.exclusions=nexusgraph/packages/nexusgraph-graph/src/GraphStyle.ts
