# sonar.host.url=https://sonarcloud.io
# sonar.organization=paion-data
# sonar.projectKey=paion-data_nexusgraph
# sonar.projectName=nexusgraph
# sonar.sources=nexusgraph
# sonar.tests=nexusgraph
# # sonar.typescript.tsconfigPath=tsconfig.json
# sonar.cpd.exclusions=nexusgraph/**/editor.spec.cy.ts
# sonar.cpd.exclusions=nexusgraph/**/GraphStyle.ts
