inputs:
  node_version:
    description: "Node Version"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set node version to ${{ inputs.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
    - name: Install dependencies
      run: yarn install
    - name: Load app environment variables
      run: |
        touch .env
        echo "NODE_ENV=development" >> .env
        echo "EXPAND_API_URL=${{ secrets.EXPAND_API_URL }}" >> .env
        echo "ENTITY_EXTRACTION_CALL_DELAY_IN_MS=$ENTITY_EXTRACTION_CALL_DELAY_IN_MS" >> .env
        echo "ENTITY_EXTRACTION_API_URL=${{ secrets.ENTITY_EXTRACTION_API_URL }}" >> .env
        echo "LOGTO_APP_ID=${{ secrets.LOGTO_APP_ID }}" >> .env
        echo "LOGTO_ENDPOINT_URL=${{ secrets.LOGTO_ENDPOINT_URL }}" >> .env
        echo "TEST_USER_NAME=${{ secrets.TEST_USER_NAME }}" >> .env
        echo "TEST_USER_PASSWORD=${{ secrets.TEST_USER_PASSWORD }}" >> .env
