# Copyright 2023 Paion Data. All rights reserved.
---
name: CI/CD

"on":
  pull_request:
  push:
    branches:
      - master
  repository_dispatch:
    types: [runbook-changes]

env:
  USER: QubitPi
  EMAIL: jack20220723@gmail.com
  NODE_VERSION: 16

jobs:
  yml-md-style:
    uses: QubitPi/hashicorp-aws/.github/workflows/yml-and-md-style-checks.yml@master

  code-style:
    name: Code Style Check
    runs-on: ubuntu-latest
    steps:
      - uses: QubitPi/hashicorp-aws/auxiliary/github/actions/ui-code-style@master
        with:
          node-version: ${{ env.NODE_VERSION }}

  unit-tests:
    name: Unit Tests
    needs: [yml-md-style, code-style]
    runs-on: ubuntu-latest
    steps:
      - uses: QubitPi/hashicorp-aws/auxiliary/github/actions/ui-unit-test@master
        with:
          node-version: ${{ env.NODE_VERSION }}

  list-e2e-specs:
    needs: unit-tests
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.list-e2e-specs.outputs.paths }}
    steps:
      - name: List Files
        id: list-e2e-specs
        uses: mirko-felice/list-files-action@v3.0.5
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: "cypress/e2e"
          ext: ".ts"

  e2e-tests:
    name: E2E Tests
    needs: list-e2e-specs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version: [16]
        start_strategy: ["yarn-start", "serve"]
        test_spec: ${{ fromJson(needs.list-e2e-specs.outputs.paths) }}
    steps:
      - uses: QubitPi/hashicorp-aws/auxiliary/github/actions/jdk-setup@master
      - uses: QubitPi/hashicorp-aws/auxiliary/github/actions/jersey-webservice-template/jpa-elide/install-data-models@master
        with:
          model-package-jar-group-id: ${{ secrets.MODEL_PACKAGE_JAR_GROUP_ID }}
          model-package-jar-artifact-id: ${{ secrets.MODEL_PACKAGE_JAR_ARTIFACT_ID }}
          model-package-jar-version: ${{ secrets.MODEL_PACKAGE_JAR_VERSION }}
          model-repo-org: ${{ secrets.MODEL_REPO_ORG }}
          models-repo-name: ${{ secrets.MODEL_REPO_NAME }}
          models-repo-token: ${{ secrets.ASTRAIOS_DATA_MODELS_REPO_TOKEN }}
      - uses: QubitPi/hashicorp-aws/auxiliary/github/actions/jersey-webservice-template/jpa-elide/docker-compose@master
        with:
          webservice-repo-clone-url: https://github.com/paion-data/astraios.git
          model-package: ${{ secrets.MODEL_PACKAGE_NAME }}
      - name: Wait until astraios Docker Compose is up
        uses: iFaxity/wait-on-action@v1
        with:
          resource: http://localhost:8080
      - uses: QubitPi/hashicorp-aws/auxiliary/github/actions/cypress-e2e@master
        with:
          node-version: ${{ env.NODE_VERSION }}
          start-strategy: ${{ matrix.start_strategy }}
          spec-relative-path: ${{ matrix.test_spec }}

  release:
    name: Publish NPM Packages
    if: github.ref == 'refs/heads/master'
    needs: e2e-tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set node version to 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          registry-url: "https://registry.npmjs.org"
      - name: Tag for release
        run: |
          git config --global user.name '$USER'
          git config --global user.email '$EMAIL'
          .github/tag-for-release.bash
      - name: Set release version
        run: |
          VERSION=$(git describe)
          npm version $VERSION
      - name: Publish to NPM Packages
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  documentation-ci-cd:
    name: Test and Deploy Documentation to GitHub Pages
    needs: e2e-tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install nexusgraph dependencies so that TypeDoc process source files properly
        run: cd ../ && yarn install
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
      - name: Install doc dependencies
        run: yarn install
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
      - name: Build documentation
        run: yarn build
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          enable_jekyll: false
          user_name: ${{ env.USER }}
          user_email: ${{ env.EMAIL }}

  hashicorp:
    name: Publish AMI Image and Deploy It to EC2 through HashiCorp
    needs: e2e-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set node version to ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Checkout HashiCorp deployment tool
        shell: bash
        run: git clone https://github.com/QubitPi/hashicorp-aws.git ../hashicorp-aws
      - name: Checkout HashiCorp deployment config files
        shell: bash
        run: git clone https://${{ secrets.RUNBOOKS_REPO_TOKEN }}@github.com/QubitPi/hashicorp-aws-runbooks.git ../hashicorp-aws-runbooks
      - name: Load Packer variable file
        shell: bash
        run: cp ../hashicorp-aws-runbooks/paion-data/nexusgraph/aws-react.pkrvars.hcl ../hashicorp-aws/hashicorp/react/images/aws-react.auto.pkrvars.hcl
      - name: Load Terraform variable file
        shell: bash
        run: cp ../hashicorp-aws-runbooks/paion-data/nexusgraph/aws-react.tfvars ../hashicorp-aws/hashicorp/react/instances/aws-react.auto.tfvars
      - name: Generate dist
        run: cp ../hashicorp-aws-runbooks/paion-data/nexusgraph/.env . && yarn && yarn build
      - name: Move dist to a location for HashiCorp deployment to pickup
        run: mv dist ../
      - name: QubitPi/hashicorp-aws
        uses: QubitPi/hashicorp-aws@master
        with:
          hashicorp-dir: ../hashicorp-aws/hashicorp/react
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
